apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
spec:
  containers:
    - name: elasticsearch-container
      image: elasticsearch
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 9200
        - containerPort: 9300
  nodeSelector:
      kubernetes.io/hostname: 5geve-k3s-master-monit
