apiVersion: v1
kind: Pod
metadata:
  name: logstash
spec:
  containers:
    - name: logstash-container
      image: logstash
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 5000
        - containerPort: 9600
        - containerPort: 8091
          hostPort: 8091
  nodeSelector:
      kubernetes.io/hostname: 5geve-k3s-master-monit
