apiVersion: v1
kind: Pod
metadata:
  name: create-kafka-topic
spec:
  containers:
    - name: create-kafka-topic-container
      image: create_kafka_topic
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8190
          hostPort: 8190
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
