apiVersion: v1
kind: Pod
metadata:
  name: dcm
spec:
  containers:
    - name: dcm-container
      image: dcm
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8090
          hostPort: 8090
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
