apiVersion: v1
kind: Pod
metadata:
  name: delete-kafka-topic
spec:
  containers:
    - name: delete-kafka-topic-container
      image: delete_kafka_topic
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8290
          hostPort: 8290
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit

