apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  containers:
    - name: kafka-consumer-container
      image: kafka_consumer
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8291
          hostPort: 8291
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
