apiVersion: v1
kind: Pod
metadata:
  name: kibana
spec:
  containers:
    - name: kibana-container
      image: kibana
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 5601
          hostPort: 5601
        - containerPort: 8080
          hostPort: 8080
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
