---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      run: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        run: zookeeper
    spec:
      containers:
        - name: zookeeper-container
          image: zookeeper
          imagePullPolicy: Never
          ports:
            - containerPort: 2181
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    run: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
  selector:
    run: zookeeper
