---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcm
spec:
  selector:
    matchLabels:
      run: dcm
  replicas: 1
  template:
    metadata:
      labels:
        run: dcm
    spec:
      containers:
        - name: dcm-container
          image: dcm
          imagePullPolicy: Never
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 3600; done;"]
          ports:
            - containerPort: 8090
              hostPort: 8090
              #  nodeSelector:
              #      kubernetes.io/hostname: tardis.tlc.pg
