apiVersion: v1
kind: Pod
metadata:
  name: dcs
spec:
  containers:
    - name: dcs-container
      image: dcs
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 8091
          hostPort: 8091
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
