---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcs
spec:
  selector:
    matchLabels:
      run: dcs
  replicas: 1
  template:
    metadata:
      labels:
        run: dcs
  spec:
    containers:
      - name: dcs-container
        image: dcs
        imagePullPolicy: Never
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 3600; done;"]
        ports:
          - containerPort: 8091
            hostPort: 8091
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
---
apiVersion: v1
kind: Service
metadata:
  name: dcs
  labels:
    run: dcs
spec:
  ports:
    - port: 8091
      protocol: TCP
  selector:
    run: dcs
