apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
    - name: kafka-container
      image: kafka:vNoRack
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 9092
#          hostPort: 9092
#      resources:
#          requests:
#              memory: "2Gi"
#              cpu: "1"
#          limits:
#              memory: "2Gi"
#              cpu: "1"
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
