---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      run: kafka
  replicas: 1
  template:
    metadata:
      labels:
        run: kafka
    spec:
      containers:
        - name: kafka-container
          image: kafka:v2
          imagePullPolicy: Never
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 3600; done;"]
          ports:
            - containerPort: 9092
#             hostPort: 9092
#           resources:
#             requests:
#               memory: "2Gi"
#               cpu: "1"
#             limits:
#               memory: "2Gi"
#               cpu: "1"
# nodeSelector:
#   kubernetes.io/hostname: tardis.tlc.pg
