apiVersion: v1
kind: Pod
metadata:
  name: logstash-pipeline-manager
spec:
  containers:
    - name: logstash-pipeline-manager-container
      image: logstash_pipeline_manager
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 5000
        - containerPort: 9600
        - containerPort: 8191
          hostPort: 8191
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
