apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
spec:
  containers:
    - name: zookeeper-container
      image: zookeeper
      imagePullPolicy: Never
      ports:
        - containerPort: 2181
#  nodeSelector:
#      kubernetes.io/hostname: 5geve-k3s-master-monit
