apiVersion: v1
kind: Pod
metadata:
  name: dcm
spec:
  containers:
    - name: dcm-simple-container
      image: dcm_simple:v2
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 3600; done;" ]
      ports:
        - containerPort: 9092
        - containerPort: 8090
          hostPort: 28090
  nodeSelector:
      kubernetes.io/hostname: 5geve-k3s-master-monit
